version: "3.8"

services:
  backend:
    build: ../backend
    container_name: backend
    image: souljump/cbumanage
    expose:
      - "8080"
    env_file:
    - ../backend/.env

  nginx:
    build:
      context: ../
      dockerfile: DevOps/nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
    environment:
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}

networks:
  cbu-net:
    driver: bridge