version: "3.8"

services:
  frontend:
    build: ../frontend
    container_name: frontend
    expose:
      - 5173

  backend:
    build: ../backend
    container_name: backend
    expose:
      - 8080

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
