version: "3.8"

services:
  backend:
    build: ../backend
    container_name: backend
    image: souljump/cbumanage
    expose:
      - "8080"
    depends_on:
      - redis

  nginx:
    build:
      context: ../
      dockerfile: DevOps/nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - cbu-net
networks:
  cbu-net:
    driver: bridge
